language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnulib
install:
  - pip install -r requirements.txt
  - pip install pylint
script:
  - pylint --errors-only --disable=print-statement mediachain
notifications:
  slack: mediachain:gzFe4w4HwIlNnxaHy1vAKW3q
  on_success: change
  on_failure: change
